import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import MainBox from "@/app/mainBoxLayout";
import Background from "@/app/background";
import {ThemeProvider} from "@mui/material";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html dir="center">
        <body
            className={"bg-purple-950 h-dvh w-full flex flex-col items-center justify-center"}
        >
        <Background/>
        <MainBox>
            {children}
        </MainBox>
        </body>
        </html>
    );
}
